- url: ${BASE_URL}/from-1-90-to-2-15-a-day-the-updated-international-poverty-line
  output: screenshots/from-1-90-to-2-15-a-day-the-updated-international-poverty-line.png
  javascript: &default_javascript |
    function () {
      return new Promise(async (resolve, reject) => {
        function sleep(ms) {
          return new Promise((resolve) => setTimeout(resolve, ms));
        }
        setTimeout(() => {
          reject(`${window.location.href} took more than 60 seconds to scroll to the end of the page and fully load.`)
        }, 60 * 1000)

        let haveAllGraphersLoaded = false
        document.addEventListener("allGraphersLoaded", () => {
          haveAllGraphersLoaded = true
        });

        while (Math.round(window.scrollY + window.innerHeight) < document.body.scrollHeight) {
          window.scrollBy(0, window.innerHeight / 4);
          await sleep(250);
        }

        while (!haveAllGraphersLoaded) {
          await sleep(500);
        }

        resolve()
      });
    }

- url: ${BASE_URL}/energy
  output: screenshots/energy.png
  javascript: *default_javascript

- url: ${BASE_URL}/life-expectancy
  output: screenshots/life-expectancy-page.png
  javascript: *default_javascript

- url: ${BASE_URL}/grapher/coal-prod-per-capita
  output: screenshots/coal-prod-per-capita-datapage.png
  javascript: *default_javascript

- url: ${BASE_URL}/births-and-deaths
  output: screenshots/births-and-deaths.png
  javascript: *default_javascript

- url: ${BASE_URL}/explorers/migration
  output: screenshots/migration-explorer.png
  javascript: *default_javascript

- url: ${BASE_URL}/
  output: screenshots/homepage.png
  javascript: *default_javascript
