- url: ${BASE_URL}/from-1-90-to-2-15-a-day-the-updated-international-poverty-line
  output: ${TARGET_DIR}/from-1-90-to-2-15-a-day-the-updated-international-poverty-line.png
  javascript: &default_javascript |
    function () {
      return new Promise(async (resolve, reject) => {
        function sleep(ms) {
          return new Promise((resolve) => setTimeout(resolve, ms));
        }
        setTimeout(() => {
          reject(`${window.location.href} took more than 60 seconds to scroll to the end of the page and fully load.`)
        }, 60 * 1000)

        while (Math.round(window.scrollY + window.innerHeight) < document.body.scrollHeight) {
          window.scrollBy(0, window.innerHeight / 4);
          await sleep(250);
        }

        while (!window._OWID_HAVE_ALL_GRAPHERS_LOADED) {
          await sleep(500);
        }

        resolve()
      });
    }

- url: ${BASE_URL}/energy
  output: ${TARGET_DIR}/energy.png
  javascript: *default_javascript

- url: ${BASE_URL}/life-expectancy
  output: ${TARGET_DIR}/life-expectancy-page.png
  javascript: *default_javascript

- url: ${BASE_URL}/grapher/tomato-production
  output: ${TARGET_DIR}/tomato-production-datapage.png
  javascript: *default_javascript

- url: ${BASE_URL}/births-and-deaths
  output: ${TARGET_DIR}/births-and-deaths.png
  javascript: *default_javascript

- url: ${BASE_URL}/explorers/migration
  output: ${TARGET_DIR}/migration-explorer.png
  javascript: *default_javascript

- url: ${BASE_URL}/
  output: ${TARGET_DIR}/homepage.png
  javascript: *default_javascript
